library(dplyr)
library(stringr)
library(readr)
library(tidyr)
library(rpart)
#library(readxl)
#library(lubridate)
library(ggplot2)
library(lattice)
library(caret)
library(car)
library(MASS)
library(cowplot)
install.packages("rpart.plot", repos='http://cran.us.r-project.org')
library(rpart.plot)
install.packages("cowplot", repos='http://cran.us.r-project.org')
library(cowplot)
install.packages("ROCR", repos='http://cran.us.r-project.org')
library(ROCR)
install.packages("e1071", repos='http://cran.us.r-project.org')
library(e1071)
install.packages("corrplot", repos='http://cran.us.r-project.org')
library(corrplot)
install.packages("randomForest", repos='http://cran.us.r-project.org')
library(randomForest)
install.packages("pROC", repos='http://cran.us.r-project.org')
library(pROC)
install.packages("ggplotify", repos='http://cran.us.r-project.org')
library(pROC)
